### ISSUE TITLE
eep! Invalid audio device ID

### ISSUE THREAD

**Issue by neuralian** [SquidSinker/GZExamples#1]
Nice work, thanks.  A fun way to learn Julia especially how to do interactive animations.  
I get no sound effects running basic.jl. Instead I see:

┌ Warning: Unable to play sound BasicGame\sounds\eep.wav
│ Invalid audio device ID
└ @ GameZero C:\Users\Admin\.julia\packages\GameZero\pYB9e\src\resources.jl:11

I'm runing Windows 10 and guessing that this is the problem. Is there a way to make play_sound() work under Windows?

**Comment by SquidSinker** [comment]
Both @aviks and I use Windows 10 and sound does work for us. 

What version of GameZero did you try this on? Could you test this in a fresh Julia session (possibly after rebooting) and check if that changes the behaviour?
